### ISSUE TITLE
Error al extraer datos FotoCasa en docker

### ISSUE THREAD

**Issue by jvruoc** [jvruoc/rent_prices#13]
En las pruebas de la extracción de datos de FotoCasa, el uso en docker no ha funcionado. Genera un error porque no localiza el elemento para hacer scroll en la página.

Para  investigarlo se incluyen varios cambios:

* Se añade argumento --html y --screenshot a la línea de comando para poder grabar lo que se recupera de la web
* Se añade parámetro --headless en el driver local (parece que resuelve problemas de errores en el driver)
* Se añade clase de configuración
* Se añade un método es Scrapy para envolver el `driver.get()` y poder grabar su contenido

**Comment by KevMCh** [comment]
No sé si es el mismo error, pero cuando estaba modificando la adquisición de datos me surgían problemas al obtener el enlace a la siguiente página (en local). En la rama _newAcquisition_ he modificado la función para la obtención de la nueva página usando la url y parece que funciona mejor, no da errores de que no encuentra el elemento.
