### ISSUE TITLE
Infraestructura lanzamiento proceso diario

### ISSUE THREAD

**Issue by KevMCh** [jvruoc/rent_prices#5]

**Comment by jvruoc** [comment]
Se incluirán las siguientes mejoras:

[ ] Empaquetado docker de la aplicación
[ ] Almacenamiento de datos en Mongo Atlas
[ ] Despliegue en Servidor del docker

### Requerimientos de la clase de scraping

* Los datos devueltos por la clase que realice el scraping tienen que ser facilitados mediante yield para no ocupar más memoria de la necesaria.
* Tiene que hacer un tratamiento recursivo si necesita la paginación

Para la implementación en docker se hará una clase TestScraping.py que implemente estos requerimientos
